const mongoose = require('mongoose');

const packageBookingSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  packageId: { type: String, required: true },
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  phone: { type: String, required: true },
  address: { type: String },
  adults: { type: Number, min: 1, required: true },
  children: { type: Number, default: 0 },
  infants: { type: Number, default: 0 },
  seniorCitizens: { type: Number, default: 0 },
  childrenAges: [{ type: Number }],
  travelDate: { type: Date, required: true },
  flexibleDates: { type: Boolean, default: false },
  alternateDate: { type: Date },
  hotelCategory: { type: String, enum: ['budget', 'standard', 'premium', 'luxury'], required: true },
  roomType: { type: String, enum: ['single', 'double', 'triple', 'family'], required: true },
  mealPlan: { type: String, enum: ['no-meals', 'breakfast', 'half-board', 'full-board'], required: true },
  transportMode: { type: String, required: true },
  pickupCity: { type: String, required: true },
  pickupAddress: { type: String },
  dietaryPreference: [{ type: String }],
  specialOccasion: { type: String },
  celebrationNote: { type: String },
  medicalNeeds: { type: String },
  budgetPerPerson: { type: Number },
  paymentMode: { type: String },
  customizationNeeded: { type: Boolean, default: false },
  customNotes: { type: String },
  idType: { type: String },
  idNumber: { type: String },
  assignedDriver: { type: mongoose.Schema.Types.ObjectId, ref: 'Driver' },
  paymentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment' },
  paymentScreenshot: { type: String },
  status: { type: String, enum: ['pending', 'confirmed', 'cancelled', 'completed'], default: 'pending' },
  totalAmount: { type: Number },
  advancePaid: { type: Number, default: 0 },
}, { timestamps: true });

module.exports = mongoose.model('PackageBooking', packageBookingSchema);
